name: Deploy Application

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed

env:
  HETZNER_INSTANCE_IP: ${{ secrets.HETZNER_INSTANCE_IP }}
  HETZNER_USER: ${{ secrets.HETZNER_USER }}

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.branch == 'main' && 'production' || 'stage' }}

    steps:
      - name: Checkout код
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Настройка на SSH връзка
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.HETZNER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host vps\n  HostName ${{ secrets.HETZNER_INSTANCE_IP }}\n  User ${{ secrets.HETZNER_USER }}\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Логин в GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Деплойване на Docker образи
        run: |
          FRONTEND_IMAGE_TAG="ghcr.io/zazemiata/zazemiata-fe:dev_latest"
          ssh vps << EOF
            # Логин в GitHub Container Registry
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            # Деплойване на фронтенд
            docker pull $FRONTEND_IMAGE_TAG
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker create --name temp-container $FRONTEND_IMAGE_TAG
            docker cp temp-container:/app/. /var/www/html/
            docker rm temp-container
            sudo nginx -s reload
            if [ -f /var/www/html/index.html ]; then
              echo "Фронтенд файловете са успешно разположени."
            else
              echo "Разполагането на фронтенда е неуспешно."
              exit 1
            fi
          EOF

