name: FullCycle Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

  build_and_push_docker_image:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lowercase Repository Name
        id: lowercase_repo
        run: echo "LOWERCASE_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set Branch and Short SHA for Docker Tags
        id: tag_info
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/\//-/g')
          SHORT_SHA=${GITHUB_SHA::5}
          echo "DOCKER_TAG_LATEST=${BRANCH_NAME}_latest" >> $GITHUB_ENV
          echo "DOCKER_TAG_SHORTSHA=${BRANCH_NAME}_${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ env.DOCKER_TAG_LATEST }} \
                       -t ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ env.DOCKER_TAG_SHORTSHA }} .

          docker push ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ env.DOCKER_TAG_LATEST }}
          docker push ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ env.DOCKER_TAG_SHORTSHA }}